support macos too

diff --git a/fetch-github-token/action.yml b/fetch-github-token/action.yml
--- a/fetch-github-token/action.yml
+++ b/fetch-github-token/action.yml
@@ -79,7 +79,9 @@ runs:
       env:
         VAULT_VERSION: "1.20.4"
       run: |
+        OS=$(uname -s | tr '[:upper:]' '[:lower:]')
         ARCH=$(uname -m)
+
         case "$ARCH" in
           x86_64)
             VAULT_ARCH="amd64"
@@ -92,10 +94,26 @@ runs:
             exit 1
             ;;
         esac
-        echo "Detected architecture: $ARCH, using Vault binary for: linux_$VAULT_ARCH"
-        curl -fsSL "https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_${VAULT_ARCH}.zip" -o vault.zip
+
+        case "$OS" in
+          linux)
+            VAULT_OS="linux"
+            INSTALL_CMD="install vault /usr/local/bin/"
+            ;;
+          darwin)
+            VAULT_OS="darwin"
+            INSTALL_CMD="install vault /usr/local/bin/"
+            ;;
+          *)
+            echo "::error title=Unsupported OS::Operating system $OS is not supported"
+            exit 1
+            ;;
+        esac
+
+        echo "Detected OS: $OS, Architecture: $ARCH, using Vault binary for: ${VAULT_OS}_${VAULT_ARCH}"
+        curl -fsSL "https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_${VAULT_OS}_${VAULT_ARCH}.zip" -o vault.zip
         unzip vault.zip
-        sudo install vault /usr/local/bin/
+        $INSTALL_CMD
         vault --version
 
     - name: Fetch GitHub Token from Vault with Retry
